table inventories
	lineageTag: 6a592965-5ac9-4e90-84a3-e17719e9fcb8

	column version
		dataType: double
		formatString: 0
		lineageTag: bd418d21-2853-41a3-955f-9a38b823352a
		summarizeBy: none
		sourceColumn: version

		annotation SummarizationSetBy = User

	column set_num
		dataType: string
		lineageTag: 9ce7bf99-7ebf-4713-a0d6-266d86e2895b
		summarizeBy: none
		sourceColumn: set_num

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column inventory_id
		dataType: double
		lineageTag: 93ae9af4-6aad-4b3e-bf14-a829da6fc6c4
		summarizeBy: none
		sourceColumn: inventory_id

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'version rev'
		dataType: double
		lineageTag: 8c86251e-e1d1-47f4-8667-63449ebcadd9
		summarizeBy: sum
		sourceColumn: version rev

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column mini_figures_name =
			
			VAR Names = SUMMARIZE(RELATEDTABLE('inventory_minifigs'), 'inventory_minifigs'[mini_figures_name])
			RETURN
			CONCATENATEX(Names, 'inventory_minifigs'[mini_figures_name], "||")
		lineageTag: 15b78e56-3e6e-449f-bdba-3823d20e9779
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column mini_figures_image =
			
			VAR Names = SUMMARIZE(RELATEDTABLE('inventory_minifigs'), 'inventory_minifigs'[mini_figures_image])
			RETURN
			CONCATENATEX(Names, 'inventory_minifigs'[mini_figures_image], "||")
		lineageTag: 55bac74a-27a5-4db9-8feb-8ef9aa760237
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column set_colors =
			
			VAR Names = SUMMARIZE(RELATEDTABLE('inventory_parts'), inventory_parts[set_colors])
			RETURN
			CONCATENATEX(Names, inventory_parts[set_colors], "||")
		lineageTag: 6dcb4116-58cc-4f6e-a4cf-18bf0e083d23
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column set_colors_rgb =
			
			VAR Names = SUMMARIZE(RELATEDTABLE('inventory_parts'), inventory_parts[set_colors_rgb])
			RETURN
			CONCATENATEX(Names, inventory_parts[set_colors_rgb], "||")
		lineageTag: 6782f92d-1ca6-4ac9-8e68-7e86eb029b77
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column part_number =
			
			VAR Names = SUMMARIZE(RELATEDTABLE('inventory_parts'), 'inventory_parts'[part_num])
			RETURN
			CONCATENATEX(Names, 'inventory_parts'[part_num], "||")
		lineageTag: 96a1f7b5-0412-4f82-b477-58f5de99edae
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column set_color_age =
			
			VAR Names = SUMMARIZE(RELATEDTABLE('inventory_parts'), 'inventory_parts'[set_colors_age])
			RETURN
			CONCATENATEX(Names, 'inventory_parts'[set_colors_age], "||")
		lineageTag: 42b2abcc-5b6b-4677-891d-16732b0a27db
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition inventories = m
		mode: import
		source = ```
				let
				    Source = Csv.Document(File.Contents("C:\Users\kanzi\Documents\Data Challenge\Power BI Data Championship\World Champs BCN 26 Round 2\Data\inventories.csv"),[Delimiter=",", Columns=3, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"id", Int64.Type}, {"version", Int64.Type}, {"set_num", type text}}),
				    #"Renamed Columns" = Table.RenameColumns(#"Changed Type",{{"id", "inventory_id"}}),
				    #"Grouped Rows" = Table.Group(#"Renamed Columns", {"set_num"}, {{"AllRowsGrouped", each Table.AddIndexColumn(
				        Table.Sort(_,{{"version", 
				        Order.Descending}}), "version rev",1,1), type table [inventory_id=nullable number, version=nullable number, set_num=nullable text,
				        version rev=nullable number]}}),
				    #"Expanded AllRowsGrouped" = Table.ExpandTableColumn(#"Grouped Rows", "AllRowsGrouped", {"inventory_id", "version", "version rev"}, {"inventory_id", "version", "version rev"})
				in
				    #"Expanded AllRowsGrouped"
				```

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

