table minifigures
	lineageTag: c981c053-8a3e-4a8d-be10-7ece70267602

	column fig_number
		dataType: string
		lineageTag: ef508c66-d09a-4ae5-a4bf-9057a5a7c6b1
		summarizeBy: none
		sourceColumn: fig_number

		annotation SummarizationSetBy = Automatic

	column minifigure_name
		dataType: string
		lineageTag: 5dead116-cfd9-4972-881e-5d41a5bbf07c
		summarizeBy: none
		sourceColumn: minifigure_name

		annotation SummarizationSetBy = Automatic

	column num_parts
		dataType: int64
		formatString: 0
		lineageTag: dfbb2c20-5bb2-4743-90d3-cccc3c4f93ef
		summarizeBy: none
		sourceColumn: num_parts

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column img_url
		dataType: string
		lineageTag: aa9ec0f5-924f-4cc3-99f2-54bc765f730a
		dataCategory: ImageUrl
		summarizeBy: none
		sourceColumn: img_url

		annotation SummarizationSetBy = Automatic

	partition minifigures = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\kanzi\Documents\Data Challenge\Power BI Data Championship\World Champs BCN 26 Round 2\Data\minifigs.csv"),[Delimiter=",", Columns=4, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"fig_num", type text}, {"name", type text}, {"num_parts", Int64.Type}, {"img_url", type text}}),
				    #"Renamed Columns" = Table.RenameColumns(#"Changed Type",{{"name", "minifigure_name"}, {"fig_num", "fig_number"}})
				in
				    #"Renamed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

