table parts
	lineageTag: 12152f8d-9bb6-4283-aa2b-eb7fec4d53da

	column part_number
		dataType: string
		lineageTag: bd702e2c-9d78-4f1a-a040-2048de181735
		summarizeBy: none
		sourceColumn: part_number

		annotation SummarizationSetBy = Automatic

	column part_name
		dataType: string
		lineageTag: 1a3e139c-c7f0-4c77-b635-2eb1ac3bbec1
		summarizeBy: none
		sourceColumn: part_name

		annotation SummarizationSetBy = Automatic

	column part_cat_id
		dataType: int64
		formatString: 0
		lineageTag: 8d7014bb-c144-49b5-9aeb-260f15d085e1
		summarizeBy: none
		sourceColumn: part_cat_id

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column part_material
		dataType: string
		lineageTag: 0aa0b59b-6962-4625-8e5c-4fe1a022f097
		summarizeBy: none
		sourceColumn: part_material

		annotation SummarizationSetBy = Automatic

	column part_category
		dataType: string
		lineageTag: d71c58d4-bb87-46bf-ba20-4140fffd5121
		summarizeBy: none
		sourceColumn: part_category

		annotation SummarizationSetBy = Automatic

	partition parts = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\kanzi\Documents\Data Challenge\Power BI Data Championship\World Champs BCN 26 Round 2\Data\parts.csv"),[Delimiter=",", Columns=4, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"part_num", type text}, {"name", type text}, {"part_cat_id", Int64.Type}, {"part_material", type text}}),
				    #"Merged Queries" = Table.NestedJoin(#"Changed Type", {"part_cat_id"}, part_categories, {"part_cat_id"}, "part_categories", JoinKind.LeftOuter),
				    #"Expanded part_categories" = Table.ExpandTableColumn(#"Merged Queries", "part_categories", {"Part Category"}, {"Part Category"}),
				    #"Renamed Columns" = Table.RenameColumns(#"Expanded part_categories",{{"name", "part_name"}, {"part_num", "part_number"}, {"Part Category", "part_category"}})
				in
				    #"Renamed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

